live_config_reload = true
import = ["~/.config/alacritty/aura-theme.toml"]

[mouse]
hide_when_typing = true

[colors]
draw_bold_text_with_bright_colors = true

[env]
TERM = "xterm-256color"

[font]
size = 15

[font.bold]
family = "Iosevka"
style = "SemiBold"

[font.bold_italic]
family = "Iosevka"
style = "Bold Italic"

[font.italic]
family = "Iosevka"
style = "Italic"

[font.normal]
family = "Iosevka"
style = "Medium"

[window]
decorations = "none"
dynamic_padding = false
opacity = 0.95

[window.dimensions]
columns = 133
lines = 40

[window.padding]
x = 0
y = 0

[shell]
program = "tmux"

[keyboard]
bindings = [{ key = "F11", action = "ToggleFullscreen" }]
