gui:
  border: single
  theme:
    activeBorderColor:
      - "#fabd2f"
      - bold
    inactiveBorderColor:
      - "#665c54"
    searchingActiveBorderColor:
      - "#8ec07c"
      - bold
    optionsTextColor:
      - "#83a598"
    selectedLineBgColor:
      - "#3c3836"
    inactiveViewSelectedLineBgColor:
      - "#504945"
    cherryPickedCommitFgColor:
      - "#83a598"
    cherryPickedCommitBgColor:
      - "#458588"
    markedBaseCommitFgColor:
      - "#83a598"
    markedBaseCommitBgColor:
      - "#d65d0e"
    unstagedChangesColor:
      - "#fb4934"
    defaultFgColor:
      - "#ebdbb2"
