add_newline = false

format = "$directory$git_status$fill$git_branch$git_commit$git_state$cmd_duration$status$line_break$character"

[fill]
symbol = " "

[directory]
format = '[\[$path\]](cyan)'
truncation_length = 0
truncate_to_repo = false

[git_branch]
format = '[\[$branch\]]($style)'
style = 'bold green'
only_attached = true

[git_commit]
format = '[\[$hash\]]($style)'
style = 'bold dimmed'
only_detached = true
tag_disabled = true

[git_state]
format = '\([$state( $progress_current/$progress_total)](bold red)\)'
rebase = 'rebase'
merge = 'merge'
revert = 'revert'
cherry_pick = 'cherry-pick'
bisect = 'bisect'
am = 'am'
am_or_rebase = 'am/rebase'

[git_status]
format = '(\[$ahead_behind[$staged$modified$renamed](yellow)[$deleted](yellow)[$untracked](yellow)[$stashed](dimmed)[$conflicted](red)\])'
ahead = '[↑](blue)'
behind = '[↓](purple)'
diverged = '[↑](blue)[↓](purple)'
up_to_date = ''
conflicted = '!'
untracked = '?'
stashed = '\$'
modified = '~'
staged = '+'
renamed = '»'
deleted = '-'
typechanged = ''

[nodejs]
disabled = true

[python]
disabled = true

[rust]
disabled = true

[cmd_duration]
min_time = 2000
format = " took [$duration]($style)"
style = "bold yellow"

[status]
disabled = false
format = " [$symbol$status]($style)"
symbol = ""
style = "red"

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
