---
# System packages playbook for dotfiles installation
# This installs all the core system packages from packages.list

- name: "Display package installation plan"
  debug:
    msg:
      - "Installing system packages for {{ ansible_distribution }}"
      - "Package manager: {{ package_manager | default('apt') }}"
      - "Total packages to install: {{ all_packages | length }}"

- name: "Update package cache"
  apt:
    update_cache: true
    cache_valid_time: 3600
  when: ansible_os_family == 'Debian'

- name: "Install core system packages"
  package:
    name: "{{ core_packages }}"
    state: present
  register: core_packages_result
  ignore_errors: true

- name: "Install CLI tools"
  package:
    name: "{{ cli_tools }}"
    state: present
  register: cli_tools_result
  ignore_errors: true

- name: "Install optional packages"
  package:
    name: "{{ optional_packages }}"
    state: present
  register: optional_packages_result
  ignore_errors: true
  when: install_flags.optional_tools | default(true)

- name: "Install development packages"
  package:
    name: "{{ development_packages }}"
    state: present
  register: dev_packages_result
  ignore_errors: true
  when: install_flags.development | default(true)

- name: "Install font packages"
  package:
    name: "{{ font_packages }}"
    state: present
  register: font_packages_result
  ignore_errors: true
  when: install_flags.gui_applications | default(true)

- name: "Install archive tools"
  package:
    name: "{{ archive_packages }}"
    state: present
  register: archive_packages_result
  ignore_errors: true

- name: "Install network tools"
  package:
    name: "{{ network_packages }}"
    state: present
  register: network_packages_result
  ignore_errors: true

- name: "Check if fd-find exists"
  command: which fdfind
  register: fdfind_check
  failed_when: false
  changed_when: false

- name: "Create fd symlink (Debian/Ubuntu)"
  file:
    src: /usr/bin/fdfind
    dest: /usr/local/bin/fd
    state: link
  when:
    - ansible_os_family == 'Debian'
    - fdfind_check.rc == 0

- name: "Check if batcat exists"
  command: which batcat
  register: batcat_check
  failed_when: false
  changed_when: false

- name: "Create bat symlink (Debian/Ubuntu)"
  file:
    src: /usr/bin/batcat
    dest: /usr/local/bin/bat
    state: link
  when:
    - ansible_os_family == 'Debian'
    - batcat_check.rc == 0

- name: "Verify package installations"
  command: "{{ item.value }}"
  register: package_verification
  failed_when: false
  changed_when: false
  loop: "{{ package_verification | dict2items }}"
  loop_control:
    label: "{{ item.key }}"

- name: "Create list of installed packages"
  set_fact:
    installed_packages: "{{ installed_packages | default([]) + [item.key] }}"
  when: item.rc == 0
  loop: "{{ package_verification.results }}"
  loop_control:
    label: "{{ item.item.key }}"

- name: "Create list of failed packages"
  set_fact:
    failed_packages: "{{ failed_packages | default([]) + [item.key] }}"
  when: item.rc != 0
  loop: "{{ package_verification.results }}"
  loop_control:
    label: "{{ item.item.key }}"

- name: "Display installation results"
  debug:
    msg:
      - "=== Package Installation Results ==="
      - "Successfully installed: {{ installed_packages | default([]) | length }} packages"
      - "Failed installations: {{ failed_packages | default([]) | length }} packages"
      - "Installed packages: {{ installed_packages | default([]) | join(', ') }}"
      - "Failed packages: {{ failed_packages | default([]) | join(', ') }}"

- name: "Update font cache"
  command: fc-cache -fv
  when:
    - font_packages_result.changed | default(false)
    - install_flags.gui_applications | default(true)
  become_user: "{{ dotfiles.user }}"

- name: "Set system packages completion fact"
  set_fact:
    system_packages_completed: true
    package_installation_summary:
      total_attempted: "{{ (core_packages | length) + (cli_tools | length) + (optional_packages | length) }}"
      successful: "{{ installed_packages | default([]) | length }}"
      failed: "{{ failed_packages | default([]) | length }}"
