live_config_reload = true
import = ["~/.config/alacritty/aura-theme.toml"]
# icon="home/gustaf/.local/share/icons/Alacritty.icns"

[env]
TERM = "xterm-256color"

[font]
size = 15

[font.bold]
family = "RobotoMono Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "RobotoMono Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "RobotoMono Nerd Font Mono"
style = "Italic"

[font.normal]
family = "RobotoMono Nerd Font Mono"
style = "Regular"

[window]
# decorations = "buttonless"
# dynamic_padding = false
# opacity = 0.9
[window.dimensions]
columns = 133
lines = 40
 
[window.padding]
#x = 25
#y = 20
